apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakaomsg
  labels:
    app: kakaomsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakaomsg
  template:
    metadata:
      labels:
        app: kakaomsg
    spec:
      containers:
        - name: kakaomsg
          image: admin35.azurecr.io/kakaomsg:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5